### ISSUE TITLE
styling: labels with long descriptions do not expand with the wrapped text

### ISSUE THREAD

**Issue by xnopasaranx** [viur-framework/viur-vi#106]
Not sure what the behaviour should be, but bone descriptions that are longer and need to wrap look funny, as the label does not envelope them then.

![image](https://user-images.githubusercontent.com/16277515/146914575-2f7df166-ebc6-4c56-81cd-cf072e2660a9.png)

It's worse when the bone is required and text is bold because of this:
![image](https://user-images.githubusercontent.com/16277515/146914840-1e7ce6b7-c3e5-40cc-baff-1bcd6e73ceb0.png)

**Comment by phneutral** [comment]
This is due to some colliding changes in the recent Vi styling update. It just needs a little fix that will come with the next Ignite push.

**Comment by akelch** [comment]
fixed in latest release
