### ISSUE TITLE
Switch Styling is broken and Unicode Characters displayed incorrectly after saving

### ISSUE THREAD

**Issue by timmytiefkuehl** [viur-framework/viur-vi#117]
![image](https://user-images.githubusercontent.com/32836039/156150591-a6611b37-7f1a-4295-9a57-88b68edd6417.png)

**Comment by sveneberth** [comment]
Not sure, but I think the switch is already fixed in the latest ignite version. Or @phneutral ?

**Comment by phneutral** [comment]
Fix is [here](https://github.com/viur-framework/viur-ignite/commit/ba51255665c02334e1be62c7aea66d7a1b512a31)

**Comment by akelch** [comment]
fixed with latest release
