### ISSUE TITLE
Implement developer mode

### ISSUE THREAD

**Issue by phorward** [viur-framework/viur-vi#13]
What about a Vi developer mode? When using Vi in developer mode, it may provide some detailed information in various places.

- Function to quickly obtain an entities key value
- Tool for generating execCalls (initialHashHandler)
- Directly jump into Google Cloud console
- Show bone names and type instead of description values

These are some first ideas.

**Comment by skoegl** [comment]
Displaying entity key, kind and shortKey should be a std feature ;)

**Comment by phorward** [comment]
I think the latest commit helps you a little more with this issue :-)

**Comment by phorward** [comment]
(see the address bar)
![image](https://user-images.githubusercontent.com/16870072/45555680-bf7bac00-b839-11e8-8364-706588c8c6cd.png)
