### ISSUE TITLE
Rootnode selector on treeBones disappear after first use

### ISSUE THREAD

**Issue by tsteinruecken** [viur-framework/viur-vi#130]
When first opening the selector popup in a treeBone, it correctly shows the rootNode selector drop-down.
![Screenshot_20220803_145840](https://user-images.githubusercontent.com/617502/182614262-bf89e36d-b774-4d4c-9828-1c56a36e5c93.png)
However, after closing and reopening the selector, that dropdown is missing.
![Screenshot_20220803_145854](https://user-images.githubusercontent.com/617502/182614345-c3a9bea8-b062-4bec-b099-106eae272601.png)

**Comment by phorward** [comment]
Fixed by dd6e320
