### ISSUE TITLE
SelectTable with no selected columns fails completely 

### ISSUE THREAD

**Issue by sveneberth** [viur-framework/viur-vi#27]
In a list you can select the columns to be displayed. So far, so good. But when you disable all columns respectively you haven't selected any column and apply it you will get an AssertionError.

```python
AssertionError: Cannot create cols with negative index
Traceback:
pyjslib.py, line 140
html5.ext.py, line 27:
    self.callback(self)
actions.list.py, line 504:
    self.listWdg.setFields( res )
widgets.list.py, line 320:
    self.table.setShownFields(fields)
widgets.table.py, line 706:
    self.rebuildTable()
widgets.table.py, line 693:
    self.table.prepareGrid( len(self._model), len(self._shownFields))
html5.core.py, line 2815:
    self.prepareCol(row, cols)
widgets.table.py, line 413:
    super( SelectTable, self ).prepareCol( row, col + self._extraCols() - 1 )
html5.core.py, line 2795:
    assert col >= 0, "Cannot create cols with negative index"
```
That means the current Pane isn't usable anymore, which is bad if this was a careless mistake, see:
![image](https://user-images.githubusercontent.com/10272292/54303741-fb62b480-45c3-11e9-9f20-062166391b0c.png)

**Comment by phorward** [comment]
it's fixed with 56f758b34118287f3958729f85ff4a71e5a53f73
