### ISSUE TITLE
Vi drops Bones which are visible=False

### ISSUE THREAD

**Issue by akelch** [viur-framework/viur-vi#3]
If a Bone is visible=False the content will be deleted from the Datastore, cause the vi does not send the Data as hidden Fields to the Server.

To reproduce: 
Set a bunch of Bones visible =True and fill them with Data.
Change the Bones to visible = False and resave the entry.
Now all Bones are empty

Here my test Bones:
t1 = stringBone(descr="str",visible=False)
t2 = stringBone( descr="strM",multiple=True, visible=False )
t3 = selectOneBone( descr="one", visible=False,values={"1":"1","2":"2"} )
t4 = selectMultiBone( descr="mult", visible=False,values={"1":"1","2":"2"} )
t5 = textBone( descr="txt", visible=False )
t6 = relationalBone( descr="rel", visible=False,kind="arel" )
t7 = relationalBone( descr="rel",multiple=True, visible=False,kind="arel" )
t8 = relationalBone( descr="rel", visible=False, kind="arel",using=useSkel )
t9 = relationalBone( descr="rel", multiple=True, visible=False, kind="arel",using=useSkel )

**Comment by phorward** [comment]
Please check out the latest develop commit, this shall fix your issue. I tested with your code supplied, it looked well 👍
