### ISSUE TITLE
Multiple or emtpy spatialBones breaks edit

### ISSUE THREAD

**Issue by tsteinruecken** [viur-framework/viur-vi#35]
Having 3 SpatialBones, "Position angezeigt" and "Position gemessen aus GPS" have the same value, yet only the first is displayed correctly.
![Screenshot_20190520_140034](https://user-images.githubusercontent.com/617502/58020148-a4b7b080-7b07-11e9-8eb9-0411c390b9dd.png)
![Screenshot_20190520_140104](https://user-images.githubusercontent.com/617502/58020183-b600bd00-7b07-11e9-990e-c289a2ca708e.png)

**Comment by phorward** [comment]
Hello, I cannot completely fix this issue for the following reason: The spatialBone is implemented in a very defective way, both on client and server-side. The default "fromClient" function is used on the server, but the bone expects to save a tuple. The current implementation sends name.lat and name.lng to the server, but these parameters are examined nowhere. Please fix the server source code first and then re-open this issue again. 

The original problem reported in this issue could not be reproduced. Tested with ViUR 2.5.
