### ISSUE TITLE
Vi must not retry POST-requests failing with error code 500

### ISSUE THREAD

**Issue by tsteinruecken** [viur-framework/viur-vi#49]
Currently, the vi automatically retries requests if it receives a non 200 status code. While this may or may not be useful for GET requests, it's an error to silently retry posts as they are not idempotent.
This can (and recently did) corrupt data.

**Comment by phorward** [comment]
Hello,

according to https://github.com/viur-framework/vi/blob/master/network.py#L104, retry is only done on the following error codes: 0, -1, 500 and 502.

0, -1 and 502 occur on network connectiviy failures. The only option which might corrupt data is 500, when something on the server stored and crashed afterwards. We could change this line to read for 0, -1 and 502 only. Any other status codes (non 200) are handled properly.

**Comment by tsteinruecken** [comment]
Please see https://groups.google.com/a/chromium.org/forum/#!topic/chromium-dev/urswDsm6Pe0 .
You *must not* retry Post-Requests unless you have *proof* the Server didn't receive or did not process the request. As we don't use the Bad Gateway code our self this may only be raised from the appengine front end servers or some 3rd party proxy in the middle, so 502 should be off that list as well. Not sure about 0 and -1 (haven't checked how browser handle these), but again: if you can't be sure the request did not process at all: don't retry.

**Comment by phorward** [comment]
Ok, in this case we do it on 0 and -1 only.

**Comment by phorward** [comment]
fixed with b6922f8c74db938219557d4aa74d3d5b635f3110
