### ISSUE TITLE
Strange things relating log and indexeddb

### ISSUE THREAD

**Issue by phorward** [viur-framework/viur-vi#82]
Hi, the current feature/viur3 branch has a serious  problem with its log and maybe the indexed-db.

I got stuck with this screen in the end:
![image](https://user-images.githubusercontent.com/16870072/89949234-e1e5f200-dc27-11ea-9634-2553e9df509d.png)

I also recognized this strange message "Task started!" that comes up every time I start a new Vi, and after the yellow "a script is slowing down"-bar has deceased. 
![image](https://user-images.githubusercontent.com/16870072/89949554-63d61b00-dc28-11ea-9c9b-f6b7bd163455.png)

In the console, the following message is also strange and repeats 1000 times:
![image](https://user-images.githubusercontent.com/16870072/89949859-d1824700-dc28-11ea-8190-c6c06edc2404.png)
Its origin is here: https://github.com/viur-framework/viur-vi/blob/feature/viur3/utils.py#L269

When I clean-up vi-cache/vi-log in indexeddb, everything works better, but after a while the problem occurs again.

**Comment by akelch** [comment]
The log is, with the last commit, limited to the last 50 entries (configurable).  When loading the Vi, the log is now cleaned up.  The visual feedback is no longer displayed at startup
